apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmak
  labels:
    app: strimzi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cmak
    spec:
      containers:
        - name: cmak
          image: openlabred/cmak:v3.0.0.5
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 9000
              name: ui
              protocol: TCP
          env:
            - name: ZK_HOSTS
              value: '127.0.0.1:2181'
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 30
        - env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'main-zookeeper-client:2181'
            - name: TLS_SIDECAR_LOG_LEVEL
              value: notice
            - name: KAFKA_CERTS_NAME
              value: cmak
          image: openlabred/cmak-stunnel:v1.0.0
          imagePullPolicy: Always
          name: tls-sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/tls-sidecar/cmak/
              name: cmak
            - mountPath: /etc/tls-sidecar/cluster-ca-certs/
              name: cluster-ca
      volumes:
        - name: cluster-ca
          secret:
            defaultMode: 288
            secretName: main-cluster-ca-cert
        - name: cmak
          secret:
            defaultMode: 288
            secretName: main-kafka-brokers
  strategy:
    type: RollingUpdate
