apiVersion: v1
kind: Service
metadata:
  labels:
    app: cmak
  name: cmak
spec:
  ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    name: cmak
  sessionAffinity: None
  type: ClusterIP
